# Generated by Django 3.0.4 on 2020-09-13 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReservacionesApp', '0004_auto_20200912_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=30)),
                ('name_prop', models.CharField(max_length=30)),
                ('num_card', models.CharField(max_length=19)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reservacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ReservacionesApp.Reservar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
