# Generated by Django 3.0.4 on 2020-09-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagar',
            old_name='user',
            new_name='usuario',
        ),
    ]
