# Generated by Django 3.0.4 on 2020-09-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_auto_20200912_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagar',
            name='usuario',
        ),
    ]
