# Generated by Django 3.0.4 on 2020-09-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_auto_20200912_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagar',
            name='usuario',
        ),
    ]
