# Generated by Django 3.0.4 on 2020-09-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.IntegerField()),
                ('niños', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateTimeField()),
            ],
        ),
    ]
