# Generated by Django 3.0.4 on 2020-09-09 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReservacionesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservar',
            name='paisOrigen',
            field=models.CharField(choices=[('Alemania', 'Alemania'), ('Canadá', 'Canadá'), ('Mexico', 'Mexico'), ('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Peru', 'Peru'), ('Ecuador', 'Ecuador'), ('Costa Rica', 'Costa Rica'), ('Estado Unidos', 'Estado Unidos'), ('España', 'España')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservar',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
