# Generated by Django 3.0.4 on 2020-09-12 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReservacionesApp', '0002_auto_20200908_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservar',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AddField(
            model_name='reservar',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
